W8D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy, :index, :show] do 
    resources :subs, only: [:edit]
  end

  resources :subs, only: [:new, :create, :update, :index, :show]


  resource :session, only:[:new, :create, :destroy]
end

W8D1/RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :description, presence:true
    validates :title, uniqueness:true

    belongs_to :moderator, 
        foreign_key: :user_id, 
        class_name: :User

end

W8D1/RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :session_token, presence:true
    validates :username, uniqueness:true
    validates :password, length: {minimum: 6, allow_nil:true}
    after_initialize :ensure_session_token
    attr_reader :password

    has_many :subs, 
        foreign_key: :user_id, 
        class_name: :Sub

    def self.find_by_credentials(username, password)
        user= User.find_by(username: username)
        user && user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password= password
        self.password_digest= BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token
        self.session_token= SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token 
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

W8D1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def current_user
        @current_user ||= user.find_by(session_token: session[:session_token])
    end
    
    def required_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login!(user)
        session[:session_token]= self.reset_session_token
    end

    def logged_in?
        !!current_user
    end

    def logout
        current_user.reset_session_token if logged_in?
        session[:session_token]= nil
        @current_user= nil
    end
end

W8D1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :required_logged_in, only: [:destroy, :create]

  def new
    render :new
  end

  def create
    user= User.find_by(id: params[:id])
    if user
      redirect_to users_url
    else
      flash.now[:errors]= ["incorrect password or username"]
      render :new
    end
  end

  def destroy
    logout
  end
end

W8D1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :required_logged_in, only: [:edit, :update, :create]
  def new
    render :new
  end

  def create
    @sub= Sub.new(sub_params)
    @sub.user_id= params[:user_id]
    if @sub.save
      redirect_to user_url(params[:id])
    else
      flash[:errors]= @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs= Sub.all
    render :index
  end

  def show
    @sub= Sub.find_by(id: params[:id])
  end

  def edit
    @sub= Sub.find_by(id: params[:id])
  end

  def update
    @sub= Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url
    else
      flash[:errors]= @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:name, :description)
  end
end

W8D1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
    render :new
  end

  def create
    @user= User.new(user_params)

    if user.save
      redirect_to users_url
    else 
      flash.now[:errors]= @user.errors.full_messages
      render :new
    end
  end

  def destroy
    user= User.find_by[id: params[:id]] 
    user.delete
  end

  def index
    @user=User.all
    render :index
  end

  def show
    @user= User.find_by[id: params[:id]] 
    render :show
  end
end

W8D1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in?%>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <button>Sign out</button>
      </form>
    <% end %>
    
    <% if flash[:errors] %>
      <%= flash[:errors].join(", ") %>
    <% end %>
    <%= yield %>
  </body>
</html>

W8D1/RedditClone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

W8D1/RedditClone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

W8D1/RedditClone/app/views/subs/index.html.erb
<h1>Subs#index</h1>
<p>Find me in app/views/subs/index.html.erb</p>

W8D1/RedditClone/app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

W8D1/RedditClone/app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

W8D1/RedditClone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

W8D1/RedditClone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

W8D1/RedditClone/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <a href="<%= user_url(user) %>"><%= user.username %></a>
        </li>

    <% end %>
</ul>

W8D1/RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
    <label>Email:
        <input name="user[username]" value="<%= @user.username %>">
    </label>

    <label>Password:
        <input type="password" name="user[password]">
    </label>

    <button>Sign Up</button>
</form>

W8D1/RedditClone/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>